<a href="https://colab.research.google.com/github/Homedepot5/DataScience/blob/deeplearning/activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import math
def sigmoid(x):
  return 1/(1+math.exp(-x))

In [4]:
sigmoid(100)

1.0

tanh

In [5]:
def tanh(x):
  return (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))

In [6]:
tanh(-56)

-1.0

In [7]:
tanh(56)

1.0


ReLU

In [9]:
def relu(x):
    return max(0,x)

In [10]:
relu(-100)

0

Leaky ReLU

In [11]:
def leaky_relu(x):
    return max(0.1*x,x)

In [12]:
leaky_relu(-100)

-10.0

In [1]:

import numpy as np


Calculate profit/loss from revenue and expenses

In [3]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [7]:
profit=revenue-expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

Calculate total sales from units and price per unit using matrix multiplication

In [9]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [10]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

Excersise

In [11]:
revenus_per_dollar=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenus_per_dollar

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [12]:
np.dot(75,revenus_per_dollar)

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [21]:
unit_sold=np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_units=np.array([[20,30,15]])

In [22]:
np.dot(price_per_units,unit_sold)

array([[1900, 2640, 1430]])

In [23]:
epsilon = 1e-15

NameError: ignored