<a href="https://colab.research.google.com/github/Homedepot5/DataScience/blob/origin%2Ffeature%2Fdevelopment/CarPricePredication_HotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CarPricePredication_HotEncoding**
and dummies variable example **bold text** **bold text**

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from google.colab import files
import io

In [2]:
uploaded=files.upload()

Saving CarPrices.csv to CarPrices.csv


In [58]:
df=pd.read_csv(io.BytesIO(uploaded['CarPrices.csv']))
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [59]:
dummeies=pd.get_dummies(df['Car Model'])
dummeies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [61]:
newdf=pd.concat([df,dummeies],axis=1)
newdf

Car Model  Mileage  ...  BMW X5  Mercedez Benz C class
0                  BMW X5    69000  ...       1                      0
1                  BMW X5    35000  ...       1                      0
2                  BMW X5    57000  ...       1                      0
3                  BMW X5    22500  ...       1                      0
4                  BMW X5    46000  ...       1                      0
5                 Audi A5    59000  ...       0                      0
6                 Audi A5    52000  ...       0                      0
7                 Audi A5    72000  ...       0                      0
8                 Audi A5    91000  ...       0                      0
9   Mercedez Benz C class    67000  ...       0                      1
10  Mercedez Benz C class    83000  ...       0                      1
11  Mercedez Benz C class    79000  ...       0                      1
12  Mercedez Benz C class    59000  ...       0                      1

[13 rows x 7 columns]

In [62]:
x=newdf.drop(df[['Car Model','Sell Price($)']],axis=1)
x

Mileage  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class
0     69000         6        0       1                      0
1     35000         3        0       1                      0
2     57000         5        0       1                      0
3     22500         2        0       1                      0
4     46000         4        0       1                      0
5     59000         5        1       0                      0
6     52000         5        1       0                      0
7     72000         6        1       0                      0
8     91000         8        1       0                      0
9     67000         6        0       0                      1
10    83000         7        0       0                      1
11    79000         7        0       0                      1
12    59000         5        0       0                      1

In [63]:
model=linear_model.LinearRegression()
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [116]:
model.fit(x,newdf[['Sell Price($)']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [117]:
model.predict([[45000,4,0,0,1]])

array([[27506770.85821721]])

BMW PRICE

In [120]:
model.predict([[8600,7,0,1,0]])

array([[5279419.74063038]])

In [121]:
model.score(x,y)

0.9417050937281083

UsingHot label Encoder 

In [66]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [74]:
dfl=df
dfl

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [79]:
dfl['Car Model']=le.fit_transform(dfl['Car Model'])
dfl

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [91]:
x=dfl[['Car Model','Mileage','Age(yrs)']].values
x

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [92]:
y=dfl['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [93]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('Car Model', OneHotEncoder(), [0])], remainder = 'passthrough')


In [94]:
x = ct.fit_transform(x)
x

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [95]:
X = x[:,1:]
X

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [97]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [113]:
model.predict([[1,4,0,45000]])

array([-59898360.66095354])