<a href="https://colab.research.google.com/github/Homedepot5/DataScience/blob/origin%2Ffeature%2Fdevelopment/exercise_one_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise_one_hot_encoding

In [180]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from google.colab import files
import io


In [181]:
uploaded=files.upload()



Saving HotEncoding_HomePrice.csv to HotEncoding_HomePrice (1).csv


In [183]:
df=pd.read_csv(io.BytesIO(uploaded['HotEncoding_HomePrice.csv']))
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [184]:
dummies=pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [185]:
merged =pd.concat([df,dummies],axis='columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [186]:
x=merged.drop(['town','west windsor','price'],axis='columns')
x

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [187]:
model=linear_model.LinearRegression()
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [188]:
merged.price

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [189]:
model.fit(x,merged.price)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [190]:
model.predict([[2600,0,1]])

array([565396.15136531])

In [191]:
model.predict([[3400,0,0]])

array([681241.66845839])

In [192]:
model.score(x,merged.price)

0.9573929037221873

**Rough. Code for string model inn flat **file  (Ignore it.))**bold text** **bold text**

In [ ]:
#from sklearn.externals import joblib
#joblib.dump(model,'HotPredication_model_joblib')

In [166]:
#mp=joblib.load('HotPredication_model_joblib')


In [ ]:
#mp.predict([[3400,0,0]])

**Using sklearn OneHotEncoder**
First step is to use label encoder to convert town names into number

In [193]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [194]:
dfl=df
dfl

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [195]:
dfl.town=le.fit_transform(dfl.town)
dfl

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [196]:
x=dfl[['area','town']].values
x


array([[2600,    0],
       [3000,    0],
       [3200,    0],
       [3600,    0],
       [4000,    0],
       [2600,    2],
       [2800,    2],
       [3300,    2],
       [3600,    2],
       [2600,    1],
       [2900,    1],
       [3100,    1],
       [3600,    1]])

In [ ]:
y=dfl.price.values
y

In [214]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')


In [215]:
x

<13x10 sparse matrix of type '<class 'numpy.float64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [ ]:
x = ct.fit_transform(x)
x

In [206]:
X = x[:,1:]

In [ ]:
X

In [ ]:
model.fit(X,y)

In [ ]:
model.predict([[3400,0,0]])