<a href="https://colab.research.google.com/github/Homedepot5/DataScience/blob/deeplearning/GradientDescent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import io

In [ ]:

df=pd.read_csv('insurance_data.csv')
df

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [39]:
X_train

age  affordibility
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1
19   18              1
25   54              1
16   25              0
20   21              1
3    52              0
7    60              0
1    25              0
5    56              1
27   46              1
8    62              1
18   19              0
12   27              0
23   45              1
22   40              1
15   55              1
26   23              1
4    46              1

In [ ]:
X_trainscaled=  X_train.copy()
X_trainscaled.age=X_trainscale['age']/100
X_testscaled=X_test.copy()
X_testscaled.age=X_testscaled['age']/100
X_trainscaled

In [42]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])


binary_crossentropy  is equal to log loss function




In [43]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_trainscaled, y_train, epochs=5000)

In [46]:
model.evaluate(X_testscaled,y_test)

1/1 [==============================] - 0s 2ms/step - loss: 0.9048 - accuracy: 0.5000


[0.9048382639884949, 0.5]

In [48]:
model.predict(X_testscaled)

array([[0.9735558 ],
       [0.8489841 ],
       [0.6371375 ],
       [0.91487575],
       [0.9766953 ],
       [0.98915493]], dtype=float32)

In [49]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [50]:
coef, intercept = model.get_weights()

In [51]:
coef, intercept

(array([[6.48021  ],
        [1.6821105]], dtype=float32), array([-1.121893], dtype=float32))

In [52]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [53]:
X_test

age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [54]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)

0.9735557416549722

In [55]:
prediction_function(.18, 1)

0.8489841045002384

In [60]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [61]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [57]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [62]:
gradient_descent(X_trainscaled['age'],X_trainscaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.9999282232360152, w2:0.971669880620831, bias:-0.0739505736380883, loss:0.678816168870839
Epoch:1, w1:0.9998965260682263, w2:0.9498750006366197, bias:-0.13800582380379656, loss:0.6671855035034422
Epoch:2, w1:0.9998997262668243, w2:0.933788962073053, bias:-0.19344848161221706, loss:0.6587026866246876
Epoch:3, w1:0.9999329383350856, w2:0.922607069790442, bias:-0.2414835096022177, loss:0.6525255258790199
Epoch:4, w1:0.9999917193180933, w2:0.9155812117428886, bias:-0.28320396592263375, loss:0.6480097738618977
Epoch:5, w1:1.000072132594069, w2:0.9120382453726881, bias:-0.319576598223008, loss:0.6446770609745633
Epoch:6, w1:1.0001707557311863, w2:0.9113865727163714, bias:-0.3514407972389579, loss:0.6421800551406165
Epoch:7, w1:1.000284654345479, w2:0.9131151235465002, bias:-0.379515600743051, loss:0.6402707484369918
Epoch:8, w1:1.0004113380098958, w2:0.9167879740721767, bias:-0.40441088700173233, loss:0.6387742281682205
Epoch:9, w1:1.0005487088744471, w2:0.9220368276451786, bias

(1.2117098523547645, 1.6856469179943665, -1.1030164779597114)