<a href="https://colab.research.google.com/github/Homedepot5/DataScience/blob/origin%2Ffeature%2Fdevelopment/LogisticRegressionBinaryClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LogisticRegressionBinaryClassification


In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from google.colab import files
import io
import matplotlib.pyplot as plt

In [20]:
uploaded=files.upload()

Saving insurance.csv to insurance (1).csv


In [34]:
df=pd.read_csv(io.BytesIO(uploaded['insurance.csv']))
df

age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [35]:
df.shape

(27, 2)

In [42]:
from sklearn.model_selection import train_test_split


In [62]:
X_train, X_test, y_train, y_test = train_test_split(df[['age']],df.bought_insurance, train_size=0.8)

In [73]:
X_train

age
2    47
13   29
7    60
12   27
11   28
1    25
8    62
10   18
22   40
16   25
4    46
9    61
24   50
3    52
18   19
23   45
17   58
0    22
15   55
5    56
25   54

In [74]:
X_test

age
26   23
6    55
14   49
21   26
19   18
20   21

In [97]:
model=linear_model.LogisticRegression()
type(model)

sklearn.linear_model._logistic.LogisticRegression

In [98]:
model.fit(X_train,y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [105]:
model.predict(X_test)

array([0, 1, 1, 0, 0, 0])

In [115]:
model.predict([[96]])

array([1])

In [118]:
model.score(X_test,y_test)

0.8333333333333334

In [101]:
X_test

age
26   23
6    55
14   49
21   26
19   18
20   21

In [102]:
model.predict_proba(X_test)

array([[0.87524492, 0.12475508],
       [0.04929064, 0.95070936],
       [0.11513861, 0.88486139],
       [0.81578713, 0.18421287],
       [0.9379041 , 0.0620959 ],
       [0.90507046, 0.09492954]])

ValueError: ignored