<a href="https://colab.research.google.com/github/Homedepot5/DataScience/blob/origin%2Ffeature%2Fdevelopment/Naive_BayesPart1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Naive Bayes for Titanic Tutorial

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from google.colab import files
import io
import matplotlib.pyplot as plt
import math

In [3]:
uploaded=files.upload()


Saving Titanic.csv to Titanic.csv


In [4]:
df=pd.read_csv(io.BytesIO(uploaded['Titanic.csv']))
df


PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [58]:
train_df=df.drop(['Survived',"Name",'PassengerId','SibSp','Parch','Ticket','Cabin','Embarked'],axis=1)
train_df

Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0   NaN  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [61]:
train_df.columns[train_df.isna().any()]

Index(['Age'], dtype='object')

In [77]:
target=df.Survived
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [57]:
from sklearn.preprocessing import LabelEncoder

In [90]:
he=LabelEncoder()
train_df['Sex']=he.fit_transform(train_df['Sex'])
train_df

Pclass  Sex        Age     Fare
0         3    1  22.000000   7.2500
1         1    0  38.000000  71.2833
2         3    0  26.000000   7.9250
3         1    0  35.000000  53.1000
4         3    1  35.000000   8.0500
..      ...  ...        ...      ...
886       2    1  27.000000  13.0000
887       1    0  19.000000  30.0000
888       3    0  29.699118  23.4500
889       1    1  26.000000  30.0000
890       3    1  32.000000   7.7500

[891 rows x 4 columns]

In [91]:
mm=train_df.Age.mean()
mm

29.699117647058763

In [92]:


train_df.Age.fillna(mm,inplace=True)

train_df


Pclass  Sex        Age     Fare
0         3    1  22.000000   7.2500
1         1    0  38.000000  71.2833
2         3    0  26.000000   7.9250
3         1    0  35.000000  53.1000
4         3    1  35.000000   8.0500
..      ...  ...        ...      ...
886       2    1  27.000000  13.0000
887       1    0  19.000000  30.0000
888       3    0  29.699118  23.4500
889       1    1  26.000000  30.0000
890       3    1  32.000000   7.7500

[891 rows x 4 columns]

In [93]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(train_df,target,test_size=0.2)

In [96]:
len(X_train)

712

In [97]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [99]:
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [100]:
model.score(X_test,y_test)

0.7262569832402235

In [104]:
model.predict([[1,	0,	38.0,	71.2833]])

array([1])

In [106]:
model.predict(X_test[:10])

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0])

In [107]:
X_test[:10]

Pclass  Sex        Age     Fare
43        2    0   3.000000  41.5792
397       2    1  46.000000  26.0000
815       1    1  29.699118   0.0000
754       2    0  48.000000  65.0000
835       1    0  39.000000  83.1583
282       3    1  16.000000   9.5000
810       3    1  26.000000   7.8875
426       2    0  28.000000  26.0000
523       1    0  44.000000  57.9792
707       1    1  42.000000  26.2875

In [108]:
model.predict_proba(X_test[:10])

array([[0.07718641, 0.92281359],
       [0.92634978, 0.07365022],
       [0.77375726, 0.22624274],
       [0.08144145, 0.91855855],
       [0.01175498, 0.98824502],
       [0.96266474, 0.03733526],
       [0.96990612, 0.03009388],
       [0.18682485, 0.81317515],
       [0.02930594, 0.97069406],
       [0.77000592, 0.22999408]])